### ISSUE TITLE
Handle get one resource with subresource with the same type

### ISSUE THREAD

**Issue by sirspock** [KnowledgeCaptureAndDiscovery/OBA_sparql#6]
The resource `a` rdf:type `Z` has a property `prop` with range `Z`
Request: get the resource `a`
Response: the resource `a`

And example can be found:
https://tinyurl.com/v8kumye

**Comment by dgarijo** [comment]
This affect all the reflexive properties A->A.
For example, we have sdm:Region sdm:partOf sdm:Region (see https://w3id.org/okn/o/sdm#partOf).
An example:
https://w3id.org/okn/i/mint/Texas is part of https://w3id.org/okn/i/mint/United_States, but the API returns the opposite relationship as well, even though it doesn't exist in the KG

**Comment by sirspock** [comment]
Fixed in the past
