### ISSUE TITLE
Use SPARQLWrapper to send query

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA_sparql#7]
We have tested with Fuseki, and we are testing with Virtuoso. Which SPARQL endpoint will we give support to?

**Comment by sirspock** [comment]
We're using the dispatchQuery method from GRLC. They sent a HTTP request to the endpoint. However, the endpoints don't share a standard (this sucks!, yes, the developer of this project usually thinks the web semantic sucks)

SPARQLWrapper is a simple Python wrapper around a SPARQL service to remotely execute your queries. It helps in creating the query invokation and, possibly, convert the result into a more manageable format.

We're going to support:

| Software          |  Support CONSTRUCT JSON/LD |
|-------------------|----------------------------|
| ClioPatria        | Yes                        |
| OpenLink Virtuoso | Yes                        |
| Fuseki            | Yes                        |
| Eclipse RDF4J     | Yes                        |
| RASQAL            |  No                        |
| Marklogic         | No                         |
| AllegroGraph      | No                         |
| 4store            | No                         |
| Blazegraph        | No                         |
| GraphDB           | Yes                        |
| Stardog           | Yes                        |

**Comment by dgarijo** [comment]
Excellent, thanks for the update. All these triplestores implement the standard, but I agree it's a shame that there is no common method for performing the query.

**Comment by sirspock** [comment]
Fixed
